# This is a basic workflow to help you get started with Actions

name: Generate PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1.0.1
        with:
          input_dir: resume
          output_dir: resume
          build_html: false
      - name: Branch name
        run: echo running on branch ${GITHUB_HEAD_REF}
      - run: git config user.name Kireyin
      - run: git config user.email kireyin@gmail.com
      - run: git add .
      - run: git commit -m "generated"
      - run: git push -u origin ${GITHUB_HEAD_REF}
