# This is a basic workflow to help you get started with Actions

name: Generate PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generatePDFResume:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull
        run: |
          git config pull.rebase true
          git pull origin HEAD:${GITHUB_HEAD_REF}
      - name: Generate PDF
        uses: baileyjm02/markdown-to-pdf@v1.0.1
        with:
          input_dir: resume
          output_dir: resume
          build_html: false
      - name: Push
        run: | 
          git config user.name Kireyin
          git config user.email kireyin@users.noreply.github.com
          git add .
          git commit -am "generated"
          git push origin HEAD:${GITHUB_HEAD_REF}
